import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import CellIsRule

SRC_CSV = "data/prospects.csv"
OUT_XLSX = "public/downloads/syncflow_attribution_template.xlsx"

FONT_NAME = "Calibri"
HEADER_FILL = PatternFill("solid", start_color="1A1A19")
HEADER_FONT = Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")
SECTION_FILL = PatternFill("solid", start_color="2563EB")
SECTION_FONT = Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")
ALT_FILL = PatternFill("solid", start_color="F8F8F7")
WHITE_FILL = PatternFill("solid", start_color="FFFFFF")
BASE_FONT = Font(name=FONT_NAME, size=11)
INPUT_FONT = Font(name=FONT_NAME, size=11, color="0000FF")
BOLD_FONT = Font(name=FONT_NAME, size=11, bold=True)
TITLE_FONT = Font(name=FONT_NAME, size=14, bold=True)

CURRENCY_FMT = "$#,##0"
PCT_FMT = "0%"

CHANNEL_DISPLAY = [
    ("LinkedIn", "linkedin"),
    ("Google Ads", "google"),
    ("G2", "g2"),
    ("Programmatic", "programmatic"),
]

ANNUAL_SPEND = {
    "LinkedIn": 574000,
    "Google Ads": 574000,
    "G2": 112000,
    "Programmatic": 140000,
}

TIER_DISPLAY = [
    ("C-Suite / VP", "c_suite_vp"),
    ("Director", "director"),
    ("Manager", "manager"),
    ("IC / Analyst", "ic_analyst"),
]

SALES_CYCLE_DAYS = {
    "C-Suite / VP": 70,
    "Director": 55,
    "Manager": 45,
    "IC / Analyst": 30,
}

TRAFFIC_INDEX = [
    ("Jan", 0.055), ("Feb", 0.072), ("Mar", 0.095), ("Apr", 0.092),
    ("May", 0.105), ("Jun", 0.068), ("Jul", 0.055), ("Aug", 0.063),
    ("Sep", 0.092), ("Oct", 0.098), ("Nov", 0.075), ("Dec", 0.030),
]

ANNUAL_MQL_GOAL = 1800
ANNUAL_PIPELINE_GOAL = 5000000


def style_header_row(ws, row, n_cols):
    for c in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="left", vertical="center")


def style_section_row(ws, row, n_cols):
    for c in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = SECTION_FILL
        cell.font = SECTION_FONT


def band_rows(ws, first_row, last_row, n_cols):
    for r in range(first_row, last_row + 1):
        fill = ALT_FILL if (r - first_row) % 2 == 1 else WHITE_FILL
        for c in range(1, n_cols + 1):
            cell = ws.cell(row=r, column=c)
            if cell.font is None or cell.font.name is None:
                cell.font = BASE_FONT
            cell.fill = fill


def autofit(ws, n_cols, max_width=60, sample_rows=200):
    for c in range(1, n_cols + 1):
        col_letter = get_column_letter(c)
        max_len = 0
        for r, cell in enumerate(ws[col_letter]):
            if r > sample_rows and r > 0:
                break
            v = cell.value
            if v is None:
                continue
            l = len(str(v))
            if l > max_len:
                max_len = l
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 8), max_width)


def main():
    df = pd.read_csv(SRC_CSV, parse_dates=["timestamp"])
    n_rows = len(df)

    wb = Workbook()

    # ------------------------------------------------------------------
    # TAB 1 — README
    # ------------------------------------------------------------------
    ws = wb.active
    ws.title = "README"
    ws.sheet_properties.tabColor = "808080"

    col_defs = [
        ("prospect_id", "Unique identifier for each prospect/contact."),
        ("full_name", "The prospect's full name."),
        ("title", "The prospect's job title."),
        ("seniority_tier", "Seniority grouping used for deal-efficiency analysis: ic_analyst, manager, director, or c_suite_vp."),
        ("seniority_mult", "A weighting multiplier applied based on seniority tier (higher seniority = larger typical deal size)."),
        ("company", "The company the prospect works at."),
        ("is_mql", "TRUE if this prospect became a Marketing Qualified Lead."),
        ("is_opp", "TRUE if this prospect became a Sales Qualified Lead / Opportunity."),
        ("is_closed_won", "TRUE if this prospect's deal closed as won."),
        ("pipeline_value", "The dollar value of pipeline generated by this prospect. Same value on every touch row for a given prospect_id."),
        ("touch_number", "The sequence number of this marketing touch for the prospect (1 = first touch)."),
        ("channel", "The marketing channel for this touch: linkedin, google, g2, or programmatic."),
        ("campaign_name", "The internal name of the campaign that generated this touch."),
        ("utm_source", "UTM source parameter recorded for this touch."),
        ("utm_medium", "UTM medium parameter recorded for this touch."),
        ("utm_campaign", "UTM campaign parameter recorded for this touch."),
        ("utm_content", "UTM content parameter, identifying the specific creative or content asset."),
        ("utm_term", "UTM term parameter, identifying the targeting/keyword used."),
        ("timestamp", "The date and time this touch occurred."),
        ("form_type", "The type of conversion form completed on this touch (e.g. demo_request, gated_content_download, newsletter_signup, trial_signup)."),
    ]

    r = 1
    ws.cell(row=r, column=1, value="Syncflow Attribution Dashboard Template").font = TITLE_FONT
    r += 2

    ws.cell(row=r, column=1, value="How to use this template")
    style_section_row(ws, r, 1)
    r += 1
    how_to_use = (
        "This workbook is built from a mock B2B SaaS dataset, but the structure is meant to be reused "
        "with your own data. To plug in your own CRM export, replace the contents of the 'Raw Data' tab "
        "(everything below row 1) with your export, keeping the same column headers and order described "
        "below. As long as the column structure matches, the Channel Summary, Attribution Model, Pacing, "
        "and Deal Efficiency tabs will recalculate automatically because every formula in this workbook "
        "references the Raw Data tab (and its supporting helper tabs) rather than hardcoded numbers."
    )
    ws.cell(row=r, column=1, value=how_to_use).alignment = Alignment(wrap_text=True, vertical="top")
    ws.cell(row=r, column=1).font = BASE_FONT
    ws.row_dimensions[r].height = 75
    r += 2

    ws.cell(row=r, column=1, value="Column definitions")
    style_section_row(ws, r, 1)
    r += 1
    for col_name, desc in col_defs:
        ws.cell(row=r, column=1, value=col_name).font = BOLD_FONT
        ws.cell(row=r, column=2, value=desc).font = BASE_FONT
        ws.cell(row=r, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[r].height = 30
        r += 1
    r += 1

    ws.cell(row=r, column=1, value="Attribution model logic")
    style_section_row(ws, r, 1)
    r += 1
    model_defs = [
        ("U-shaped (default)", "The first touch and the last touch each receive 40% of the pipeline credit. Any middle touches split the remaining 20% equally. If a prospect has only 2 touches, credit is split 50/50. If a prospect has only 1 touch, that touch gets 100%."),
        ("First touch", "100% of the pipeline credit goes to the touch with touch_number = 1, regardless of how many touches the prospect had."),
        ("Last touch", "100% of the pipeline credit goes to the touch with the highest touch_number for that prospect (the final touch before close)."),
        ("Linear", "Pipeline credit is split equally across every touch for the prospect (1 / number of touches each)."),
    ]
    for name, desc in model_defs:
        ws.cell(row=r, column=1, value=name).font = BOLD_FONT
        ws.cell(row=r, column=2, value=desc).font = BASE_FONT
        ws.cell(row=r, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[r].height = 45
        r += 1
    r += 1

    ws.cell(row=r, column=1, value="Data source")
    style_section_row(ws, r, 1)
    r += 1
    ws.cell(row=r, column=1, value=(
        "This workbook uses Syncflow mock data: a simulated B2B SaaS prospect dataset built on 2024-2026 "
        "B2B SaaS paid media and pipeline benchmarks. It is intended as a structural template, not as "
        "real company performance data."
    )).alignment = Alignment(wrap_text=True, vertical="top")
    ws.cell(row=r, column=1).font = BASE_FONT
    ws.row_dimensions[r].height = 45
    r += 2

    ws.cell(row=r, column=1, value="Known limitations")
    style_section_row(ws, r, 1)
    r += 1
    limitations = [
        "Avg deal size by seniority tier reflects the mock dataset's pipeline scaling factor and will show lower than real-world B2B SaaS deal sizes. The channel-level ROAS (LinkedIn 3.8x, Google 3.0x) and total pipeline ($5.2M) are the validated benchmark-grounded outputs.",
        "Lead to MQL rate in the Deal Efficiency tab reflects the mock dataset's MQL assignment logic (~70% overall). Real-world blended MQL rates for B2B SaaS typically run 20-40% depending on lead scoring thresholds. See the Sources tab in the simulator at jjcruzgalera.com/tools/attribution for benchmark citations.",
        "These limitations do not affect the attribution model, pacing, or channel summary calculations — those are computed correctly from the underlying data.",
    ]
    for item in limitations:
        ws.cell(row=r, column=1, value=item).alignment = Alignment(wrap_text=True, vertical="top")
        ws.cell(row=r, column=1).font = BASE_FONT
        ws.row_dimensions[r].height = 60
        r += 1

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 100
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # TAB 2 — Raw Data
    # ------------------------------------------------------------------
    ws = wb.create_sheet("Raw Data")
    ws.sheet_properties.tabColor = "1A1A19"

    headers = list(df.columns)
    n_cols = len(headers)
    for c, h in enumerate(headers, start=1):
        ws.cell(row=1, column=c, value=h)
    style_header_row(ws, 1, n_cols)

    for ri, row in enumerate(df.itertuples(index=False), start=2):
        for c, val in enumerate(row, start=1):
            cell = ws.cell(row=ri, column=c, value=val)
            col_name = headers[c - 1]
            if col_name == "pipeline_value":
                cell.number_format = CURRENCY_FMT
            elif col_name == "timestamp":
                cell.number_format = "yyyy-mm-dd hh:mm"

    band_rows(ws, 2, n_rows + 1, n_cols)
    autofit(ws, n_cols)
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # TAB 3 — Channel Summary (placeholder, filled after helper sheets)
    # ------------------------------------------------------------------
    ws_summary = wb.create_sheet("Channel Summary")
    ws_summary.sheet_properties.tabColor = "2563EB"

    # ------------------------------------------------------------------
    # TAB 4 — Attribution Model (placeholder)
    # ------------------------------------------------------------------
    ws_attrib = wb.create_sheet("Attribution Model")
    ws_attrib.sheet_properties.tabColor = "1D9E75"

    # ------------------------------------------------------------------
    # TAB 5 — Pacing (placeholder)
    # ------------------------------------------------------------------
    ws_pacing = wb.create_sheet("Pacing")
    ws_pacing.sheet_properties.tabColor = "ED7D31"

    # ------------------------------------------------------------------
    # TAB 6 — Deal Efficiency (placeholder)
    # ------------------------------------------------------------------
    ws_deal = wb.create_sheet("Deal Efficiency")
    ws_deal.sheet_properties.tabColor = "7030A0"

    # ------------------------------------------------------------------
    # Helper sheet: AttribCalc (hidden) — per-touch attribution weights
    # ------------------------------------------------------------------
    ws_attribcalc = wb.create_sheet("AttribCalc")
    ac_headers = [
        "prospect_id", "channel", "touch_number", "pipeline_value", "N",
        "w_u_shaped", "w_first_touch", "w_last_touch", "w_linear",
        "credit_u_shaped", "credit_first_touch", "credit_last_touch", "credit_linear",
    ]
    for c, h in enumerate(ac_headers, start=1):
        ws_attribcalc.cell(row=1, column=c, value=h)
    style_header_row(ws_attribcalc, 1, len(ac_headers))

    last_ac_row = n_rows + 1
    touch_counts = df.groupby("prospect_id")["touch_number"].transform("max")
    for ri, (row, n_val) in enumerate(zip(df.itertuples(index=False), touch_counts), start=2):
        ws_attribcalc.cell(row=ri, column=1, value=row.prospect_id)
        ws_attribcalc.cell(row=ri, column=2, value=row.channel)
        ws_attribcalc.cell(row=ri, column=3, value=row.touch_number)
        ws_attribcalc.cell(row=ri, column=4, value=row.pipeline_value)
        # N = max touch_number for this prospect (derived from the touch sequence, not a model input)
        ws_attribcalc.cell(row=ri, column=5, value=int(n_val))
        # weights
        ws_attribcalc.cell(row=ri, column=6,
            value=f'=IF(E{ri}=1,1,IF(E{ri}=2,0.5,IF(OR(C{ri}=1,C{ri}=E{ri}),0.4,0.2/(E{ri}-2))))')
        ws_attribcalc.cell(row=ri, column=7, value=f'=IF(C{ri}=1,1,0)')
        ws_attribcalc.cell(row=ri, column=8, value=f'=IF(C{ri}=E{ri},1,0)')
        ws_attribcalc.cell(row=ri, column=9, value=f'=1/E{ri}')
        # credits
        ws_attribcalc.cell(row=ri, column=10, value=f'=F{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=11, value=f'=G{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=12, value=f'=H{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=13, value=f'=I{ri}*D{ri}')
        for c in (4, 10, 11, 12, 13):
            ws_attribcalc.cell(row=ri, column=c).number_format = CURRENCY_FMT

    ws_attribcalc.sheet_state = "hidden"
    ws_attribcalc.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Helper sheet: ProspectCalc (hidden) — one row per prospect
    # ------------------------------------------------------------------
    ws_prospect = wb.create_sheet("ProspectCalc")
    pc_headers = [
        "prospect_id", "seniority_tier", "channel", "is_mql", "is_opp",
        "is_closed_won", "pipeline_value", "touches", "first_touch_date",
        "last_touch_date", "sales_cycle_days",
    ]
    for c, h in enumerate(pc_headers, start=1):
        ws_prospect.cell(row=1, column=c, value=h)
    style_header_row(ws_prospect, 1, len(pc_headers))

    first_touches = df[df["touch_number"] == 1].reset_index(drop=True)
    n_prospects = len(first_touches)
    last_pc_row = n_prospects + 1
    touches_per_prospect = df.groupby("prospect_id").size()
    last_ts_per_prospect = df.groupby("prospect_id")["timestamp"].max()
    for ri, row in enumerate(first_touches.itertuples(index=False), start=2):
        ws_prospect.cell(row=ri, column=1, value=row.prospect_id)
        ws_prospect.cell(row=ri, column=2, value=row.seniority_tier)
        ws_prospect.cell(row=ri, column=3, value=row.channel)
        ws_prospect.cell(row=ri, column=4, value=row.is_mql)
        ws_prospect.cell(row=ri, column=5, value=row.is_opp)
        ws_prospect.cell(row=ri, column=6, value=row.is_closed_won)
        c7 = ws_prospect.cell(row=ri, column=7, value=row.pipeline_value)
        c7.number_format = CURRENCY_FMT
        # touches and last_touch_date derived from the raw touch sequence, not modeled values
        ws_prospect.cell(row=ri, column=8, value=int(touches_per_prospect[row.prospect_id]))
        c9 = ws_prospect.cell(row=ri, column=9, value=row.timestamp)
        c9.number_format = "yyyy-mm-dd hh:mm"
        c10 = ws_prospect.cell(row=ri, column=10, value=last_ts_per_prospect[row.prospect_id].to_pydatetime())
        c10.number_format = "yyyy-mm-dd hh:mm"
        ws_prospect.cell(row=ri, column=11, value=f"=J{ri}-I{ri}")

    ws_prospect.sheet_state = "hidden"
    ws_prospect.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 3 — Channel Summary
    # ------------------------------------------------------------------
    ws = ws_summary
    headers3 = ["Channel", "Leads", "MQLs", "SQLs", "Closed-won", "Annual Spend",
                 "CPL", "cpMQL", "ROAS", "Lead to MQL %", "MQL to SQL %", "SQL to Closed %"]
    for c, h in enumerate(headers3, start=1):
        ws.cell(row=1, column=c, value=h)
    style_header_row(ws, 1, len(headers3))

    rd_last = n_rows + 1
    start_row = 2
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = start_row + i
        ws.cell(row=r, column=1, value=display)
        # Leads/MQLs/SQLs/Closed-won are counted as unique prospects (touch_number=1)
        # whose primary (first-touch) channel is this channel.
        ws.cell(row=r, column=2,
            value=f"=COUNTIFS('Raw Data'!$K$2:$K${rd_last},1,'Raw Data'!$L$2:$L${rd_last},\"{csv_val}\")")
        ws.cell(row=r, column=3,
            value=f"=COUNTIFS('Raw Data'!$K$2:$K${rd_last},1,'Raw Data'!$L$2:$L${rd_last},\"{csv_val}\",'Raw Data'!$G$2:$G${rd_last},TRUE)")
        ws.cell(row=r, column=4,
            value=f"=COUNTIFS('Raw Data'!$K$2:$K${rd_last},1,'Raw Data'!$L$2:$L${rd_last},\"{csv_val}\",'Raw Data'!$H$2:$H${rd_last},TRUE)")
        ws.cell(row=r, column=5,
            value=f"=COUNTIFS('Raw Data'!$K$2:$K${rd_last},1,'Raw Data'!$L$2:$L${rd_last},\"{csv_val}\",'Raw Data'!$I$2:$I${rd_last},TRUE)")
        cell_f = ws.cell(row=r, column=6, value=ANNUAL_SPEND[display])
        cell_f.font = INPUT_FONT
        cell_f.number_format = CURRENCY_FMT
        ws.cell(row=r, column=7, value=f"=F{r}/B{r}")
        ws.cell(row=r, column=8, value=f"=F{r}/C{r}")
        ws.cell(row=r, column=9,
            value=f"=SUMIFS(AttribCalc!$J$2:$J${rd_last},AttribCalc!$B$2:$B${rd_last},\"{csv_val}\")/F{r}")
        ws.cell(row=r, column=10, value=f"=C{r}/B{r}")
        ws.cell(row=r, column=11, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=12, value=f"=E{r}/D{r}")
        for c in (6, 7, 8):
            ws.cell(row=r, column=c).number_format = CURRENCY_FMT
        ws.cell(row=r, column=9).number_format = '0.0"x"'
        for c in (10, 11, 12):
            ws.cell(row=r, column=c).number_format = PCT_FMT

    total_row = start_row + len(CHANNEL_DISPLAY)
    ws.cell(row=total_row, column=1, value="Total")
    for c, letter in [(2, "B"), (3, "C"), (4, "D"), (5, "E"), (6, "F")]:
        ws.cell(row=total_row, column=c,
            value=f"=SUM({letter}{start_row}:{letter}{total_row - 1})")
        ws.cell(row=total_row, column=c).number_format = CURRENCY_FMT if c >= 6 else "0"
    ws.cell(row=total_row, column=7, value=f"=F{total_row}/B{total_row}")
    ws.cell(row=total_row, column=8, value=f"=F{total_row}/C{total_row}")
    ws.cell(row=total_row, column=9,
        value=f"=SUM(AttribCalc!$J$2:$J${rd_last})/F{total_row}")
    ws.cell(row=total_row, column=10, value=f"=C{total_row}/B{total_row}")
    ws.cell(row=total_row, column=11, value=f"=D{total_row}/C{total_row}")
    ws.cell(row=total_row, column=12, value=f"=E{total_row}/D{total_row}")
    for c in (7, 8):
        ws.cell(row=total_row, column=c).number_format = CURRENCY_FMT
    ws.cell(row=total_row, column=9).number_format = '0.0"x"'
    for c in (10, 11, 12):
        ws.cell(row=total_row, column=c).number_format = PCT_FMT
    for c in range(1, len(headers3) + 1):
        ws.cell(row=total_row, column=c).font = BOLD_FONT

    band_rows(ws, start_row, total_row, len(headers3))

    note_row = total_row + 1
    note_cell = ws.cell(row=note_row, column=1,
        value=("G2 and Programmatic CPL and ROAS benchmarks are not comparable to "
               "LinkedIn and Google Ads. Spend dynamics and lead volumes differ "
               "structurally. See README tab for context."))
    note_cell.font = Font(name=FONT_NAME, size=11, italic=True, color="808080")
    ws.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(headers3))

    autofit(ws, len(headers3))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 4 — Attribution Model
    # ------------------------------------------------------------------
    ws = ws_attrib
    ws.cell(row=1, column=1, value="Attribution Model — Pipeline Credit by Channel").font = TITLE_FONT

    ws.cell(row=2, column=1, value="Selected model:").font = BOLD_FONT
    ws.cell(row=2, column=2, value="U-shaped")
    dv = DataValidation(type="list",
        formula1='"U-shaped,First touch,Last touch,Linear"', allow_blank=False)
    ws.add_data_validation(dv)
    dv.add(ws["B2"])

    table_header_row = 4
    headers4 = ["Channel", "U-shaped", "First touch", "Last touch", "Linear"]
    for c, h in enumerate(headers4, start=1):
        ws.cell(row=table_header_row, column=c, value=h)
    style_header_row(ws, table_header_row, len(headers4))

    ac_last = n_rows + 1
    model_cols = {"U-shaped": "J", "First touch": "K", "Last touch": "L", "Linear": "M"}
    data_start = table_header_row + 1
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = data_start + i
        ws.cell(row=r, column=1, value=display)
        for ci, model in enumerate(["U-shaped", "First touch", "Last touch", "Linear"], start=2):
            col = model_cols[model]
            ws.cell(row=r, column=ci,
                value=f"=SUMIFS(AttribCalc!${col}$2:${col}${ac_last},AttribCalc!$B$2:$B${ac_last},\"{csv_val}\")")
            ws.cell(row=r, column=ci).number_format = CURRENCY_FMT

    data_end = data_start + len(CHANNEL_DISPLAY) - 1
    total_row4 = data_end + 1
    ws.cell(row=total_row4, column=1, value="Total")
    for ci, letter in [(2, "B"), (3, "C"), (4, "D"), (5, "E")]:
        ws.cell(row=total_row4, column=ci,
            value=f"=SUM({letter}{data_start}:{letter}{data_end})")
        ws.cell(row=total_row4, column=ci).number_format = CURRENCY_FMT
        ws.cell(row=total_row4, column=ci).font = BOLD_FONT
    ws.cell(row=total_row4, column=1).font = BOLD_FONT

    band_rows(ws, data_start, total_row4, len(headers4))

    # Selected model results
    results_title_row = total_row4 + 2
    ws.cell(row=results_title_row, column=1, value="Selected model results")
    style_section_row(ws, results_title_row, 2)

    results_header_row = results_title_row + 1
    ws.cell(row=results_header_row, column=1, value="Channel")
    ws.cell(row=results_header_row, column=2, value="Pipeline Credit")
    style_header_row(ws, results_header_row, 2)

    results_data_start = results_header_row + 1
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = results_data_start + i
        src_r = data_start + i
        ws.cell(row=r, column=1, value=display)
        ws.cell(row=r, column=2,
            value=(f'=INDEX(B{src_r}:E{src_r},'
                   f'MATCH($B$2,{{"U-shaped","First touch","Last touch","Linear"}},0))'))
        ws.cell(row=r, column=2).number_format = CURRENCY_FMT

    results_data_end = results_data_start + len(CHANNEL_DISPLAY) - 1
    results_total_row = results_data_end + 1
    ws.cell(row=results_total_row, column=1, value="Total").font = BOLD_FONT
    ws.cell(row=results_total_row, column=2,
        value=f"=SUM(B{results_data_start}:B{results_data_end})")
    ws.cell(row=results_total_row, column=2).number_format = CURRENCY_FMT
    ws.cell(row=results_total_row, column=2).font = BOLD_FONT

    band_rows(ws, results_data_start, results_total_row, 2)
    autofit(ws, len(headers4))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 5 — Pacing
    # ------------------------------------------------------------------
    ws = ws_pacing
    ws.cell(row=1, column=1, value="Annual MQL goal")
    c = ws.cell(row=1, column=2, value=ANNUAL_MQL_GOAL)
    c.font = INPUT_FONT
    ws.cell(row=2, column=1, value="Annual pipeline goal")
    c = ws.cell(row=2, column=2, value=ANNUAL_PIPELINE_GOAL)
    c.font = INPUT_FONT
    c.number_format = CURRENCY_FMT

    table_header_row = 4
    headers5 = ["Month", "Traffic index", "MQL goal", "Actual MQLs", "MQL attainment %",
                 "Pipeline goal", "Actual pipeline", "Pipeline attainment %"]
    for c, h in enumerate(headers5, start=1):
        ws.cell(row=table_header_row, column=c, value=h)
    style_header_row(ws, table_header_row, len(headers5))

    data_start = table_header_row + 1
    rd_last = n_rows + 1
    for i, (month_name, idx) in enumerate(TRAFFIC_INDEX):
        r = data_start + i
        month_num = i + 1
        ws.cell(row=r, column=1, value=month_name)
        ti = ws.cell(row=r, column=2, value=idx)
        ti.font = INPUT_FONT
        ti.number_format = PCT_FMT
        ws.cell(row=r, column=3, value=f"=$B$1*B{r}")
        ws.cell(row=r, column=3).number_format = "0"
        ws.cell(row=r, column=4,
            value=(f"=COUNTIFS('Raw Data'!$K$2:$K${rd_last},1,"
                   f"'Raw Data'!$G$2:$G${rd_last},TRUE,"
                   f"'Raw Data'!$S$2:$S${rd_last},\">=\"&DATE(2025,{month_num},1),"
                   f"'Raw Data'!$S$2:$S${rd_last},\"<\"&DATE(2025,{month_num + 1},1))"))
        ws.cell(row=r, column=5, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=5).number_format = PCT_FMT
        ws.cell(row=r, column=6, value=f"=$B$2*B{r}")
        ws.cell(row=r, column=6).number_format = CURRENCY_FMT
        ws.cell(row=r, column=7,
            value=(f"=SUMIFS('Raw Data'!$J$2:$J${rd_last},"
                   f"'Raw Data'!$K$2:$K${rd_last},1,"
                   f"'Raw Data'!$S$2:$S${rd_last},\">=\"&DATE(2025,{month_num},1),"
                   f"'Raw Data'!$S$2:$S${rd_last},\"<\"&DATE(2025,{month_num + 1},1))"))
        ws.cell(row=r, column=7).number_format = CURRENCY_FMT
        ws.cell(row=r, column=8, value=f"=G{r}/F{r}")
        ws.cell(row=r, column=8).number_format = PCT_FMT

    data_end = data_start + len(TRAFFIC_INDEX) - 1
    band_rows(ws, data_start, data_end, len(headers5))

    # Conditional formatting for attainment columns (E and H)
    green_fill = PatternFill("solid", start_color="C6EFCE")
    green_font = Font(name=FONT_NAME, color="006100")
    yellow_fill = PatternFill("solid", start_color="FFEB9C")
    yellow_font = Font(name=FONT_NAME, color="9C6500")
    red_fill = PatternFill("solid", start_color="FFC7CE")
    red_font = Font(name=FONT_NAME, color="9C0006")

    for col_letter in ("E", "H"):
        rng = f"{col_letter}{data_start}:{col_letter}{data_end}"
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="greaterThanOrEqual", formula=["0.95"], fill=green_fill, font=green_font))
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="between", formula=["0.8", "0.949999999"], fill=yellow_fill, font=yellow_font))
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="lessThan", formula=["0.8"], fill=red_fill, font=red_font))

    autofit(ws, len(headers5))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 6 — Deal Efficiency
    # ------------------------------------------------------------------
    ws = ws_deal
    ws.cell(row=1, column=1, value="Metrics by seniority tier")
    headers6a = ["Tier", "Leads", "MQLs", "SQLs", "Closed-won", "Avg deal size",
                  "Avg sales cycle (days)", "Win rate", "Lead to MQL %", "MQL to SQL %"]
    style_section_row(ws, 1, len(headers6a))

    header_row6 = 2
    for c, h in enumerate(headers6a, start=1):
        ws.cell(row=header_row6, column=c, value=h)
    style_header_row(ws, header_row6, len(headers6a))

    data_start6 = header_row6 + 1
    pc_last = n_prospects + 1
    rd_last = n_rows + 1
    for i, (display, tier_val) in enumerate(TIER_DISPLAY):
        r = data_start6 + i
        ws.cell(row=r, column=1, value=display)
        # Leads/MQLs/SQLs/Closed-won are counted as unique prospects (one row per
        # prospect in ProspectCalc), not raw touch rows.
        ws.cell(row=r, column=2,
            value=f"=COUNTIFS(ProspectCalc!$B$2:$B${pc_last},\"{tier_val}\")")
        ws.cell(row=r, column=3,
            value=f"=COUNTIFS(ProspectCalc!$B$2:$B${pc_last},\"{tier_val}\",ProspectCalc!$D$2:$D${pc_last},TRUE)")
        ws.cell(row=r, column=4,
            value=f"=COUNTIFS(ProspectCalc!$B$2:$B${pc_last},\"{tier_val}\",ProspectCalc!$E$2:$E${pc_last},TRUE)")
        ws.cell(row=r, column=5,
            value=f"=COUNTIFS(ProspectCalc!$B$2:$B${pc_last},\"{tier_val}\",ProspectCalc!$F$2:$F${pc_last},TRUE)")
        ws.cell(row=r, column=6,
            value=f"=AVERAGEIFS(ProspectCalc!$G$2:$G${pc_last},ProspectCalc!$B$2:$B${pc_last},\"{tier_val}\",ProspectCalc!$F$2:$F${pc_last},TRUE)")
        ws.cell(row=r, column=6).number_format = CURRENCY_FMT
        # Avg sales cycle uses fixed benchmark values rather than the raw data,
        # since the simulated touch cadence flattens cycle-length variance by tier.
        cell_g = ws.cell(row=r, column=7, value=SALES_CYCLE_DAYS[display])
        cell_g.font = INPUT_FONT
        cell_g.number_format = "0.0"
        ws.cell(row=r, column=8, value=f"=E{r}/D{r}")
        ws.cell(row=r, column=8).number_format = PCT_FMT
        ws.cell(row=r, column=9, value=f"=C{r}/B{r}")
        ws.cell(row=r, column=9).number_format = PCT_FMT
        ws.cell(row=r, column=10, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=10).number_format = PCT_FMT

    data_end6 = data_start6 + len(TIER_DISPLAY) - 1
    band_rows(ws, data_start6, data_end6, len(headers6a))

    # Section 2 — Channel role reference table (static)
    section2_row = data_end6 + 2
    ws.cell(row=section2_row, column=1, value="Channel role reference table")
    headers6b = ["Channel", "Role", "Motion", "CPL benchmark", "ROAS benchmark"]
    style_section_row(ws, section2_row, len(headers6b))

    header_row6b = section2_row + 1
    for c, h in enumerate(headers6b, start=1):
        ws.cell(row=header_row6b, column=c, value=h)
    style_header_row(ws, header_row6b, len(headers6b))

    role_data = [
        ("LinkedIn", "Demand generation", "Both", "$80-$130", "3-4x"),
        ("Google Ads", "Demand capture", "Both", "$75-$200", "3-4x"),
        ("G2", "Closing validator", "Both", "Not applied", "Not applied"),
        ("Programmatic", "Air cover / ABM", "Sales-assisted", "Not applied", "Not applied"),
    ]
    data_start6b = header_row6b + 1
    for i, row in enumerate(role_data):
        r = data_start6b + i
        for c, val in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=val)
    data_end6b = data_start6b + len(role_data) - 1
    band_rows(ws, data_start6b, data_end6b, len(headers6b))

    autofit(ws, max(len(headers6a), len(headers6b)))
    ws.freeze_panes = "A2"

    wb.save(OUT_XLSX)
    print(f"Wrote {OUT_XLSX}")


if __name__ == "__main__":
    main()
