import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import CellIsRule

from seasonality import (
    SEASONALITY_INDEX, FISCAL_MONTHS, FISCAL_MONTH_NAMES,
    ANNUAL_MQL_GOAL, ANNUAL_PQL_GOAL, ANNUAL_PIPELINE_GOAL,
)

SRC_CSV = "data/prospects.csv"
OUT_XLSX = "public/downloads/syncflow_attribution_template.xlsx"

FONT_NAME = "Calibri"
HEADER_FILL = PatternFill("solid", start_color="1A1A19")
HEADER_FONT = Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")
SECTION_FILL = PatternFill("solid", start_color="2563EB")
SECTION_FONT = Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")
ALT_FILL = PatternFill("solid", start_color="F8F8F7")
WHITE_FILL = PatternFill("solid", start_color="FFFFFF")
BASE_FONT = Font(name=FONT_NAME, size=11)
INPUT_FONT = Font(name=FONT_NAME, size=11, color="0000FF")
BOLD_FONT = Font(name=FONT_NAME, size=11, bold=True)
TITLE_FONT = Font(name=FONT_NAME, size=14, bold=True)

CURRENCY_FMT = "$#,##0"
PCT_FMT = "0%"

CHANNEL_DISPLAY = [
    ("LinkedIn", "linkedin"),
    ("Google Ads", "google"),
    ("G2", "g2"),
    ("Programmatic", "programmatic"),
]

ANNUAL_SPEND = {
    "LinkedIn": 574000,
    "Google Ads": 574000,
    "G2": 112000,
    "Programmatic": 140000,
}

TIER_DISPLAY = [
    ("C-Suite / VP", "c_suite_vp"),
    ("Director", "director"),
    ("Manager", "manager"),
    ("IC / Analyst", "ic_analyst"),
]

# Fiscal-window date bounds, as spreadsheet DATE() literals.
FISCAL_START_DATE = "DATE(2025,2,1)"
FISCAL_END_DATE_EXCL = "DATE(2026,2,1)"  # exclusive upper bound


def style_header_row(ws, row, n_cols):
    for c in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="left", vertical="center")


def style_section_row(ws, row, n_cols):
    for c in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = SECTION_FILL
        cell.font = SECTION_FONT


def band_rows(ws, first_row, last_row, n_cols):
    for r in range(first_row, last_row + 1):
        fill = ALT_FILL if (r - first_row) % 2 == 1 else WHITE_FILL
        for c in range(1, n_cols + 1):
            cell = ws.cell(row=r, column=c)
            if cell.font is None or cell.font.name is None:
                cell.font = BASE_FONT
            cell.fill = fill


def autofit(ws, n_cols, max_width=60, sample_rows=200):
    for c in range(1, n_cols + 1):
        col_letter = get_column_letter(c)
        max_len = 0
        for r, cell in enumerate(ws[col_letter]):
            if r > sample_rows and r > 0:
                break
            v = cell.value
            if v is None:
                continue
            l = len(str(v))
            if l > max_len:
                max_len = l
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 8), max_width)


def main():
    df = pd.read_csv(SRC_CSV, parse_dates=["timestamp", "mql_date", "pql_date", "qualified_date", "close_date"])
    n_rows = len(df)

    wb = Workbook()

    # ------------------------------------------------------------------
    # TAB 1 — README
    # ------------------------------------------------------------------
    ws = wb.active
    ws.title = "README"
    ws.sheet_properties.tabColor = "808080"

    col_defs = [
        ("prospect_id", "Unique identifier for each prospect/contact."),
        ("full_name", "The prospect's full name."),
        ("title", "The prospect's job title."),
        ("seniority_tier", "Seniority grouping used for deal-efficiency analysis: ic_analyst, manager, director, or c_suite_vp."),
        ("seniority_mult", "A weighting multiplier applied based on seniority tier (higher seniority = larger typical deal size)."),
        ("company", "The company the prospect works at."),
        ("is_mql", "TRUE if this prospect has a touch with form_type = demo_request. This is the sole MQL definition — there is no seniority-based or probabilistic override."),
        ("is_opp", "TRUE if this prospect became a Sales Qualified Lead / Opportunity. Not gated on is_mql — a prospect with neither an MQL nor PQL touch can still become an opportunity (the 'neither' lead_type segment)."),
        ("is_closed_won", "TRUE if this prospect's deal closed as won."),
        ("pipeline_value", "The dollar value of pipeline generated by this prospect. Same value on every touch row for a given prospect_id. Zero for non-opportunities."),
        ("touch_number", "The sequence number of this marketing touch for the prospect (1 = first touch), resequenced with no gaps after post-MQL suppression removes any rows."),
        ("channel", "The marketing channel for this touch: linkedin, google, g2, or programmatic."),
        ("campaign_name", "The internal name of the campaign that generated this touch."),
        ("utm_source", "UTM source parameter recorded for this touch."),
        ("utm_medium", "UTM medium parameter recorded for this touch."),
        ("utm_campaign", "UTM campaign parameter recorded for this touch."),
        ("utm_content", "UTM content parameter, identifying the specific creative or content asset."),
        ("utm_term", "UTM term parameter, identifying the targeting/keyword used."),
        ("timestamp", "The date and time this touch occurred."),
        ("form_type", "The type of conversion form completed on this touch (e.g. demo_request, gated_content_download, newsletter_signup, trial_signup)."),
        ("lead_type", "Derived from is_mql/is_pql: demo (MQL only), trial (PQL only), both, or neither. Drives conversion-rate, cycle-time, and deal-size economics."),
        ("mql_date", "Timestamp of the touch with form_type = demo_request. Blank if is_mql is FALSE."),
        ("pql_date", "Timestamp of the touch with form_type = trial_signup. Blank if is_pql is FALSE. Tracked independently of mql_date — a prospect can have both."),
        ("qualified_date", "The earliest of mql_date and pql_date where both exist; otherwise whichever one exists; otherwise the first-touch date. Always populated. This is the date pipeline value is fit against (see Known limitations)."),
        ("is_pql", "TRUE if this prospect has a touch with form_type = trial_signup."),
        ("post_mql", "TRUE if this touch's timestamp is after the prospect's mql_date. Used to scope attribution eligibility — a post-MQL touch on linkedin/google/g2 cannot exist (those channels are suppressed after MQL); a post-MQL programmatic touch (ABM air cover, not suppressed) is excluded from first-touch and last-touch attribution credit and treated as a middle touch."),
        ("cycle_days", "Seniority-based cycle base + lead_type addend, +/-15% noise. Populated for opportunities only (blank otherwise)."),
        ("close_date", "qualified_date + cycle_days. If this would fall after the Feb 28, 2026 runway end, is_closed_won is forced FALSE (the deal stays open) rather than the row being dropped."),
        ("in_fiscal_window", "TRUE if this prospect's qualified_date falls inside the fiscal reporting window (Feb 2025 - Jan 2026). This is the single population-membership gate used, together with each metric's own date field, to scope every reported number in this workbook to the fiscal year. See Known limitations."),
    ]

    r = 1
    ws.cell(row=r, column=1, value="Syncflow Attribution Dashboard Template").font = TITLE_FONT
    r += 2

    ws.cell(row=r, column=1, value="How to use this template")
    style_section_row(ws, r, 1)
    r += 1
    how_to_use = (
        "This workbook is built from a mock B2B SaaS dataset, but the structure is meant to be reused "
        "with your own data. To plug in your own CRM export, replace the contents of the 'Raw Data' tab "
        "(everything below row 1) with your export, keeping the same column headers and order described "
        "below. As long as the column structure matches, the Channel Summary, Attribution Model, Pacing & "
        "Goals, and Deal Efficiency tabs will recalculate automatically because every formula in this "
        "workbook references the Raw Data tab (and its supporting helper tabs) rather than hardcoded numbers."
    )
    ws.cell(row=r, column=1, value=how_to_use).alignment = Alignment(wrap_text=True, vertical="top")
    ws.cell(row=r, column=1).font = BASE_FONT
    ws.row_dimensions[r].height = 75
    r += 2

    ws.cell(row=r, column=1, value="Column definitions")
    style_section_row(ws, r, 1)
    r += 1
    for col_name, desc in col_defs:
        ws.cell(row=r, column=1, value=col_name).font = BOLD_FONT
        ws.cell(row=r, column=2, value=desc).font = BASE_FONT
        ws.cell(row=r, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[r].height = 30
        r += 1
    r += 1

    ws.cell(row=r, column=1, value="Attribution model logic")
    style_section_row(ws, r, 1)
    r += 1
    model_defs = [
        ("U-shaped (default)", "The first touch and the last touch each receive 40% of the pipeline credit. Any middle touches split the remaining 20% equally. If a prospect has only 2 touches, credit is split 50/50. If a prospect has only 1 touch, that touch gets 100%. A post-MQL programmatic touch is never eligible for the first- or last-touch position — it always falls into the middle-touch bucket."),
        ("First touch", "100% of the pipeline credit goes to the earliest touch NOT flagged post_mql (in practice this is almost always touch_number = 1, since the MQL/PQL touch itself is never after its own mql_date)."),
        ("Last touch", "100% of the pipeline credit goes to the latest touch NOT flagged post_mql — deliberately skipping any trailing post-MQL programmatic touches so ABM air cover can't collect last-touch credit it isn't meant to be eligible for."),
        ("Linear", "Pipeline credit is split equally across every touch for the prospect (1 / number of touches each), post-MQL touches included."),
    ]
    for name, desc in model_defs:
        ws.cell(row=r, column=1, value=name).font = BOLD_FONT
        ws.cell(row=r, column=2, value=desc).font = BASE_FONT
        ws.cell(row=r, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[r].height = 45
        r += 1
    r += 1

    ws.cell(row=r, column=1, value="Data source")
    style_section_row(ws, r, 1)
    r += 1
    ws.cell(row=r, column=1, value=(
        "This workbook uses Syncflow mock data: a simulated B2B SaaS prospect dataset built on 2024-2026 "
        "B2B SaaS paid media and pipeline benchmarks. It is intended as a structural template, not as "
        "real company performance data."
    )).alignment = Alignment(wrap_text=True, vertical="top")
    ws.cell(row=r, column=1).font = BASE_FONT
    ws.row_dimensions[r].height = 45
    r += 2

    ws.cell(row=r, column=1, value="Known limitations")
    style_section_row(ws, r, 1)
    r += 1
    limitations = [
        "MQL is defined strictly as having a demo_request touch, and PQL as having a trial_signup touch — "
        "tracked independently, so a prospect can be both. Every reported number in this workbook (Summary, "
        "Channel Summary, Pacing & Goals, Deal Efficiency, and every derived metric — CPL, cpMQL, ROAS, "
        "conversion rates) is scoped to the fiscal reporting window (Feb 2025 - Jan 2026): leads by first-touch "
        "date, MQLs by mql_date, PQLs by pql_date, pipeline by qualified_date. A record can exist in Raw Data "
        "without appearing in any of those totals if its relevant date falls outside the window.",
        "Raw Data includes an October-December 2024 warm-up cohort. It exists so February 2025 (the first "
        "fiscal month) isn't artificially thin: without leads already in-flight before the window opens, only "
        "prospects first-touched in February itself could possibly qualify that month, undercounting it relative "
        "to every other month. Warm-up-cohort touches are genuine and do feed attribution for any prospect that "
        "goes on to qualify inside the window — but the warm-up prospects themselves are excluded from every "
        "reported total unless their qualifying event (mql_date/pql_date) lands inside the fiscal window.",
        "pipeline_value is fit to a monthly pipeline target by qualified_date, not by close_date. Real-world "
        "MQL-to-opportunity lag (and the fact that a deal's pipeline is typically recognized when it enters the "
        "pipeline, not when it's fully qualified) is not modeled — this is a simplification of the underlying "
        "target-first generation method, not a real timing effect.",
        "This dataset is generated target-first: annual MQL/PQL/pipeline goals and monthly attainment curves "
        "are inputs, and individual prospect records are the mechanism that satisfies them, rather than "
        "emerging from independent per-prospect random draws whose aggregate is measured afterward. This means "
        "record-level statistical independence is not modeled — e.g., which specific prospects become "
        "opportunities in a given month is influenced by what that month's pipeline target requires. Aggregate "
        "monthly and channel-level numbers are the validated output; treating any single row as an independent "
        "random draw is not a valid use of this data.",
        "These limitations do not affect the arithmetic in the attribution model, pacing, or channel summary "
        "calculations — those are computed correctly and consistently from the underlying data, all filtered by "
        "the same in_fiscal_window rule.",
    ]
    for item in limitations:
        ws.cell(row=r, column=1, value=item).alignment = Alignment(wrap_text=True, vertical="top")
        ws.cell(row=r, column=1).font = BASE_FONT
        ws.row_dimensions[r].height = 75
        r += 1

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 100
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # TAB 2 — Raw Data
    # ------------------------------------------------------------------
    ws = wb.create_sheet("Raw Data")
    ws.sheet_properties.tabColor = "1A1A19"

    headers = list(df.columns)
    n_cols = len(headers)
    for c, h in enumerate(headers, start=1):
        ws.cell(row=1, column=c, value=h)
    style_header_row(ws, 1, n_cols)

    date_cols = {"timestamp", "mql_date", "pql_date", "qualified_date", "close_date"}
    for ri, row in enumerate(df.itertuples(index=False), start=2):
        for c, val in enumerate(row, start=1):
            col_name = headers[c - 1]
            if col_name in date_cols and pd.isna(val):
                cell = ws.cell(row=ri, column=c, value=None)
                continue
            cell = ws.cell(row=ri, column=c, value=val)
            if col_name == "pipeline_value":
                cell.number_format = CURRENCY_FMT
            elif col_name in date_cols:
                cell.number_format = "yyyy-mm-dd hh:mm"

    band_rows(ws, 2, n_rows + 1, n_cols)
    autofit(ws, n_cols)
    ws.freeze_panes = "A2"

    col_letter = {name: get_column_letter(i + 1) for i, name in enumerate(headers)}

    # ------------------------------------------------------------------
    # TAB 3 — Channel Summary (placeholder, filled after helper sheets)
    # ------------------------------------------------------------------
    ws_summary = wb.create_sheet("Channel Summary")
    ws_summary.sheet_properties.tabColor = "2563EB"

    # ------------------------------------------------------------------
    # TAB 4 — Attribution Model (placeholder)
    # ------------------------------------------------------------------
    ws_attrib = wb.create_sheet("Attribution Model")
    ws_attrib.sheet_properties.tabColor = "1D9E75"

    # ------------------------------------------------------------------
    # TAB 5 — Pacing & Goals (placeholder)
    # ------------------------------------------------------------------
    ws_pacing = wb.create_sheet("Pacing & Goals")
    ws_pacing.sheet_properties.tabColor = "ED7D31"

    # ------------------------------------------------------------------
    # TAB 6 — Deal Efficiency (placeholder)
    # ------------------------------------------------------------------
    ws_deal = wb.create_sheet("Deal Efficiency")
    ws_deal.sheet_properties.tabColor = "7030A0"

    # ------------------------------------------------------------------
    # Helper sheet: AttribCalc (hidden) — per-touch attribution weights,
    # scoped to in-window opportunities only (in_fiscal_window carried
    # over from Raw Data so downstream SUMIFS can filter on it).
    #
    # First/last-touch position is NOT simply touch_number=1 / touch_number=N:
    # a post-MQL programmatic touch (ABM air cover, exempt from suppression)
    # can legitimately be the chronologically-last surviving touch, but it
    # must never collect first- or last-touch credit — it's a middle touch
    # for U-shaped and ineligible for the first_touch/last_touch models
    # entirely. first_eligible_tn/last_eligible_tn (MINIFS/MAXIFS over
    # touch_number, filtered to post_mql=FALSE) find the true first/last
    # ELIGIBLE position per prospect; touch_number=1 is never post_mql (the
    # qualifying touch can't happen before its own mql_date), so
    # first_eligible_tn is always 1 — only last_eligible_tn can differ from
    # touch_number=N, but that's exactly the case that matters.
    # ------------------------------------------------------------------
    ws_attribcalc = wb.create_sheet("AttribCalc")
    ac_headers = [
        "prospect_id", "channel", "touch_number", "pipeline_value", "N",
        "post_mql", "first_eligible_tn", "last_eligible_tn",
        "w_u_shaped", "w_first_touch", "w_last_touch", "w_linear",
        "credit_u_shaped", "credit_first_touch", "credit_last_touch", "credit_linear",
        "in_fiscal_window",
    ]
    for c, h in enumerate(ac_headers, start=1):
        ws_attribcalc.cell(row=1, column=c, value=h)
    style_header_row(ws_attribcalc, 1, len(ac_headers))

    last_ac_row = n_rows + 1
    touch_counts = df.groupby("prospect_id")["touch_number"].transform("max")
    for ri, (row, n_val) in enumerate(zip(df.itertuples(index=False), touch_counts), start=2):
        ws_attribcalc.cell(row=ri, column=1, value=row.prospect_id)
        ws_attribcalc.cell(row=ri, column=2, value=row.channel)
        ws_attribcalc.cell(row=ri, column=3, value=row.touch_number)
        ws_attribcalc.cell(row=ri, column=4, value=row.pipeline_value)
        ws_attribcalc.cell(row=ri, column=5, value=int(n_val))
        ws_attribcalc.cell(row=ri, column=6, value=bool(row.post_mql))
        ws_attribcalc.cell(row=ri, column=7,
            value=f"=MINIFS($C$2:$C${last_ac_row},$A$2:$A${last_ac_row},A{ri},$F$2:$F${last_ac_row},FALSE)")
        ws_attribcalc.cell(row=ri, column=8,
            value=f"=MAXIFS($C$2:$C${last_ac_row},$A$2:$A${last_ac_row},A{ri},$F$2:$F${last_ac_row},FALSE)")
        ws_attribcalc.cell(row=ri, column=9,
            value=(f'=IF(E{ri}=1,1,'
                   f'IF(G{ri}=H{ri},IF(C{ri}=G{ri},0.8,0.2/(E{ri}-1)),'
                   f'IF(OR(C{ri}=G{ri},C{ri}=H{ri}),IF(E{ri}=2,0.5,0.4),0.2/(E{ri}-2))))'))
        ws_attribcalc.cell(row=ri, column=10, value=f'=IF(C{ri}=G{ri},1,0)')
        ws_attribcalc.cell(row=ri, column=11, value=f'=IF(C{ri}=H{ri},1,0)')
        ws_attribcalc.cell(row=ri, column=12, value=f'=1/E{ri}')
        ws_attribcalc.cell(row=ri, column=13, value=f'=I{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=14, value=f'=J{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=15, value=f'=K{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=16, value=f'=L{ri}*D{ri}')
        ws_attribcalc.cell(row=ri, column=17, value=bool(row.in_fiscal_window))
        for c in (4, 13, 14, 15, 16):
            ws_attribcalc.cell(row=ri, column=c).number_format = CURRENCY_FMT

    ws_attribcalc.sheet_state = "hidden"
    ws_attribcalc.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Helper sheet: ProspectCalc (hidden) — one row per prospect
    # ------------------------------------------------------------------
    ws_prospect = wb.create_sheet("ProspectCalc")
    pc_headers = [
        "prospect_id", "seniority_tier", "channel", "is_mql", "is_opp",
        "is_closed_won", "pipeline_value", "touches", "first_touch_date",
        "last_touch_date", "mql_date", "pql_date", "qualified_date",
        "is_pql", "lead_type", "cycle_days", "close_date", "in_fiscal_window",
    ]
    for c, h in enumerate(pc_headers, start=1):
        ws_prospect.cell(row=1, column=c, value=h)
    style_header_row(ws_prospect, 1, len(pc_headers))

    first_touches = df[df["touch_number"] == 1].reset_index(drop=True)
    n_prospects = len(first_touches)
    last_pc_row = n_prospects + 1
    touches_per_prospect = df.groupby("prospect_id").size()
    last_ts_per_prospect = df.groupby("prospect_id")["timestamp"].max()
    for ri, row in enumerate(first_touches.itertuples(index=False), start=2):
        ws_prospect.cell(row=ri, column=1, value=row.prospect_id)
        ws_prospect.cell(row=ri, column=2, value=row.seniority_tier)
        ws_prospect.cell(row=ri, column=3, value=row.channel)
        ws_prospect.cell(row=ri, column=4, value=row.is_mql)
        ws_prospect.cell(row=ri, column=5, value=row.is_opp)
        ws_prospect.cell(row=ri, column=6, value=row.is_closed_won)
        c7 = ws_prospect.cell(row=ri, column=7, value=row.pipeline_value)
        c7.number_format = CURRENCY_FMT
        ws_prospect.cell(row=ri, column=8, value=int(touches_per_prospect[row.prospect_id]))
        c9 = ws_prospect.cell(row=ri, column=9, value=row.timestamp)
        c9.number_format = "yyyy-mm-dd hh:mm"
        c10 = ws_prospect.cell(row=ri, column=10, value=last_ts_per_prospect[row.prospect_id].to_pydatetime())
        c10.number_format = "yyyy-mm-dd hh:mm"
        c11 = ws_prospect.cell(row=ri, column=11, value=(None if pd.isna(row.mql_date) else row.mql_date))
        c11.number_format = "yyyy-mm-dd hh:mm"
        c12 = ws_prospect.cell(row=ri, column=12, value=(None if pd.isna(row.pql_date) else row.pql_date))
        c12.number_format = "yyyy-mm-dd hh:mm"
        c13 = ws_prospect.cell(row=ri, column=13, value=row.qualified_date)
        c13.number_format = "yyyy-mm-dd hh:mm"
        ws_prospect.cell(row=ri, column=14, value=row.is_pql)
        ws_prospect.cell(row=ri, column=15, value=row.lead_type)
        ws_prospect.cell(row=ri, column=16, value=(None if pd.isna(row.cycle_days) else row.cycle_days))
        c17 = ws_prospect.cell(row=ri, column=17, value=(None if pd.isna(row.close_date) else row.close_date))
        c17.number_format = "yyyy-mm-dd hh:mm"
        ws_prospect.cell(row=ri, column=18, value=bool(row.in_fiscal_window))

    ws_prospect.sheet_state = "hidden"
    ws_prospect.freeze_panes = "A2"
    PC = {name: get_column_letter(i + 1) for i, name in enumerate(pc_headers)}

    # ------------------------------------------------------------------
    # Fill TAB 3 — Channel Summary (fiscal-window scoped)
    # ------------------------------------------------------------------
    ws = ws_summary
    headers3 = ["Channel", "Leads", "MQLs", "SQLs", "Closed-won", "Pipeline",
                "Annual Spend", "CPL", "cpMQL", "ROAS",
                "Lead to MQL %", "MQL to SQL %", "SQL to Closed %"]
    for c, h in enumerate(headers3, start=1):
        ws.cell(row=1, column=c, value=h)
    style_header_row(ws, 1, len(headers3))

    pc_last = last_pc_row
    ac_last = last_ac_row
    start_row = 2
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = start_row + i
        ws.cell(row=r, column=1, value=display)
        # Leads: scoped by first-touch date AND in_fiscal_window.
        ws.cell(row=r, column=2, value=(
            f"=COUNTIFS(ProspectCalc!${PC['channel']}$2:${PC['channel']}${pc_last},\"{csv_val}\","
            f"ProspectCalc!${PC['first_touch_date']}$2:${PC['first_touch_date']}${pc_last},\">=\"&{FISCAL_START_DATE},"
            f"ProspectCalc!${PC['first_touch_date']}$2:${PC['first_touch_date']}${pc_last},\"<\"&{FISCAL_END_DATE_EXCL},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        # MQLs: scoped by mql_date AND in_fiscal_window (mql_date can be
        # in-window even when first_touch_date is not — a warm-up prospect
        # whose qualifying touch lagged into the fiscal window).
        ws.cell(row=r, column=3, value=(
            f"=COUNTIFS(ProspectCalc!${PC['channel']}$2:${PC['channel']}${pc_last},\"{csv_val}\","
            f"ProspectCalc!${PC['is_mql']}$2:${PC['is_mql']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\">=\"&{FISCAL_START_DATE},"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\"<\"&{FISCAL_END_DATE_EXCL},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        # SQLs (opportunities): scoped by in_fiscal_window (== qualified_date in window).
        ws.cell(row=r, column=4, value=(
            f"=COUNTIFS(ProspectCalc!${PC['channel']}$2:${PC['channel']}${pc_last},\"{csv_val}\","
            f"ProspectCalc!${PC['is_opp']}$2:${PC['is_opp']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=5, value=(
            f"=COUNTIFS(ProspectCalc!${PC['channel']}$2:${PC['channel']}${pc_last},\"{csv_val}\","
            f"ProspectCalc!${PC['is_closed_won']}$2:${PC['is_closed_won']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        # Pipeline: attribution-WEIGHTED credit (U-shaped), from AttribCalc,
        # scoped to in-window opportunities — NOT a raw SUMIFS of
        # pipeline_value by the opportunity's primary channel. Using the raw
        # per-prospect total here would double-count against every other
        # channel that touched the same opportunity and silently break ROAS
        # (each touch's channel would get 0% or 100% of the deal instead of
        # its attributed share).
        ws.cell(row=r, column=6, value=(
            f"=SUMIFS(AttribCalc!$M$2:$M${ac_last},"
            f"AttribCalc!$B$2:$B${ac_last},\"{csv_val}\","
            f"AttribCalc!$Q$2:$Q${ac_last},TRUE)"))
        cell_g = ws.cell(row=r, column=7, value=ANNUAL_SPEND[display])
        cell_g.font = INPUT_FONT
        cell_g.number_format = CURRENCY_FMT
        ws.cell(row=r, column=8, value=f"=G{r}/B{r}")
        ws.cell(row=r, column=9, value=f"=G{r}/C{r}")
        ws.cell(row=r, column=10, value=f"=F{r}/G{r}")
        ws.cell(row=r, column=11, value=f"=C{r}/B{r}")
        ws.cell(row=r, column=12, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=13, value=f"=E{r}/D{r}")
        for c in (6, 7, 8, 9):
            ws.cell(row=r, column=c).number_format = CURRENCY_FMT
        ws.cell(row=r, column=10).number_format = '0.0"x"'
        for c in (11, 12, 13):
            ws.cell(row=r, column=c).number_format = PCT_FMT

    total_row = start_row + len(CHANNEL_DISPLAY)
    ws.cell(row=total_row, column=1, value="Total")
    for c, letter in [(2, "B"), (3, "C"), (4, "D"), (5, "E"), (6, "F"), (7, "G")]:
        ws.cell(row=total_row, column=c,
            value=f"=SUM({letter}{start_row}:{letter}{total_row - 1})")
        ws.cell(row=total_row, column=c).number_format = CURRENCY_FMT if c >= 6 else "0"
    ws.cell(row=total_row, column=8, value=f"=G{total_row}/B{total_row}")
    ws.cell(row=total_row, column=9, value=f"=G{total_row}/C{total_row}")
    ws.cell(row=total_row, column=10, value=f"=F{total_row}/G{total_row}")
    ws.cell(row=total_row, column=11, value=f"=C{total_row}/B{total_row}")
    ws.cell(row=total_row, column=12, value=f"=D{total_row}/C{total_row}")
    ws.cell(row=total_row, column=13, value=f"=E{total_row}/D{total_row}")
    for c in (8, 9):
        ws.cell(row=total_row, column=c).number_format = CURRENCY_FMT
    ws.cell(row=total_row, column=10).number_format = '0.0"x"'
    for c in (11, 12, 13):
        ws.cell(row=total_row, column=c).number_format = PCT_FMT
    for c in range(1, len(headers3) + 1):
        ws.cell(row=total_row, column=c).font = BOLD_FONT

    band_rows(ws, start_row, total_row, len(headers3))

    note_row = total_row + 1
    note_cell = ws.cell(row=note_row, column=1,
        value=("All figures are scoped to the fiscal window (Feb 2025 - Jan 2026) — see README. "
               "G2 and Programmatic CPL and ROAS benchmarks are not comparable to LinkedIn and Google "
               "Ads; spend dynamics and lead volumes differ structurally. See README tab for context."))
    note_cell.font = Font(name=FONT_NAME, size=11, italic=True, color="808080")
    ws.merge_cells(start_row=note_row, start_column=1, end_row=note_row, end_column=len(headers3))

    autofit(ws, len(headers3))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 4 — Attribution Model (fiscal-window scoped via AttribCalc!Q)
    # ------------------------------------------------------------------
    ws = ws_attrib
    ws.cell(row=1, column=1, value="Attribution Model — Pipeline Credit by Channel (fiscal window only)").font = TITLE_FONT

    ws.cell(row=2, column=1, value="Selected model:").font = BOLD_FONT
    ws.cell(row=2, column=2, value="U-shaped")
    dv = DataValidation(type="list",
        formula1='"U-shaped,First touch,Last touch,Linear"', allow_blank=False)
    ws.add_data_validation(dv)
    dv.add(ws["B2"])

    table_header_row = 4
    headers4 = ["Channel", "U-shaped", "First touch", "Last touch", "Linear"]
    for c, h in enumerate(headers4, start=1):
        ws.cell(row=table_header_row, column=c, value=h)
    style_header_row(ws, table_header_row, len(headers4))

    model_cols = {"U-shaped": "M", "First touch": "N", "Last touch": "O", "Linear": "P"}
    data_start = table_header_row + 1
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = data_start + i
        ws.cell(row=r, column=1, value=display)
        for ci, model in enumerate(["U-shaped", "First touch", "Last touch", "Linear"], start=2):
            col = model_cols[model]
            ws.cell(row=r, column=ci,
                value=(f"=SUMIFS(AttribCalc!${col}$2:${col}${ac_last},"
                       f"AttribCalc!$B$2:$B${ac_last},\"{csv_val}\","
                       f"AttribCalc!$Q$2:$Q${ac_last},TRUE)"))
            ws.cell(row=r, column=ci).number_format = CURRENCY_FMT

    data_end = data_start + len(CHANNEL_DISPLAY) - 1
    total_row4 = data_end + 1
    ws.cell(row=total_row4, column=1, value="Total")
    for ci, letter in [(2, "B"), (3, "C"), (4, "D"), (5, "E")]:
        ws.cell(row=total_row4, column=ci,
            value=f"=SUM({letter}{data_start}:{letter}{data_end})")
        ws.cell(row=total_row4, column=ci).number_format = CURRENCY_FMT
        ws.cell(row=total_row4, column=ci).font = BOLD_FONT
    ws.cell(row=total_row4, column=1).font = BOLD_FONT

    band_rows(ws, data_start, total_row4, len(headers4))

    results_title_row = total_row4 + 2
    ws.cell(row=results_title_row, column=1, value="Selected model results")
    style_section_row(ws, results_title_row, 2)

    results_header_row = results_title_row + 1
    ws.cell(row=results_header_row, column=1, value="Channel")
    ws.cell(row=results_header_row, column=2, value="Pipeline Credit")
    style_header_row(ws, results_header_row, 2)

    results_data_start = results_header_row + 1
    for i, (display, csv_val) in enumerate(CHANNEL_DISPLAY):
        r = results_data_start + i
        src_r = data_start + i
        ws.cell(row=r, column=1, value=display)
        ws.cell(row=r, column=2,
            value=(f'=INDEX(B{src_r}:E{src_r},'
                   f'MATCH($B$2,{{"U-shaped","First touch","Last touch","Linear"}},0))'))
        ws.cell(row=r, column=2).number_format = CURRENCY_FMT

    results_data_end = results_data_start + len(CHANNEL_DISPLAY) - 1
    results_total_row = results_data_end + 1
    ws.cell(row=results_total_row, column=1, value="Total").font = BOLD_FONT
    ws.cell(row=results_total_row, column=2,
        value=f"=SUM(B{results_data_start}:B{results_data_end})")
    ws.cell(row=results_total_row, column=2).number_format = CURRENCY_FMT
    ws.cell(row=results_total_row, column=2).font = BOLD_FONT

    band_rows(ws, results_data_start, results_total_row, 2)
    autofit(ws, len(headers4))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 5 — Pacing & Goals: three goals (MQL, PQL, Pipeline),
    # each distributed monthly by SEASONALITY_INDEX, fiscal months only.
    # ------------------------------------------------------------------
    ws = ws_pacing
    ws.cell(row=1, column=1, value="Annual MQL goal")
    c = ws.cell(row=1, column=2, value=ANNUAL_MQL_GOAL)
    c.font = INPUT_FONT
    ws.cell(row=2, column=1, value="Annual PQL goal")
    c = ws.cell(row=2, column=2, value=ANNUAL_PQL_GOAL)
    c.font = INPUT_FONT
    ws.cell(row=3, column=1, value="Annual pipeline goal")
    c = ws.cell(row=3, column=2, value=ANNUAL_PIPELINE_GOAL)
    c.font = INPUT_FONT
    c.number_format = CURRENCY_FMT

    table_header_row = 5
    headers5 = ["Month", "Seasonality Index",
                "MQL Goal", "Actual MQLs", "MQL Attainment %",
                "PQL Goal", "Actual PQLs", "PQL Attainment %",
                "Pipeline Goal", "Actual Pipeline", "Pipeline Attainment %"]
    for c, h in enumerate(headers5, start=1):
        ws.cell(row=table_header_row, column=c, value=h)
    style_header_row(ws, table_header_row, len(headers5))

    data_start = table_header_row + 1
    seasonality_map = dict(SEASONALITY_INDEX)
    for i, (ty, tm) in enumerate(FISCAL_MONTHS):
        r = data_start + i
        month_name = FISCAL_MONTH_NAMES[i]
        idx = seasonality_map[month_name]
        month_start = f"DATE({ty},{tm},1)"
        next_y, next_m = (ty + 1, 1) if tm == 12 else (ty, tm + 1)
        month_end_excl = f"DATE({next_y},{next_m},1)"

        ws.cell(row=r, column=1, value=f"{month_name} {ty}")
        ti = ws.cell(row=r, column=2, value=idx)
        ti.font = INPUT_FONT
        ti.number_format = PCT_FMT

        # MQL goal / actual / attainment
        ws.cell(row=r, column=3, value=f"=$B$1*B{r}")
        ws.cell(row=r, column=3).number_format = "0"
        ws.cell(row=r, column=4, value=(
            f"=COUNTIFS(ProspectCalc!${PC['is_mql']}$2:${PC['is_mql']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\">=\"&{month_start},"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\"<\"&{month_end_excl},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=5, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=5).number_format = PCT_FMT

        # PQL goal / actual / attainment
        ws.cell(row=r, column=6, value=f"=$B$2*B{r}")
        ws.cell(row=r, column=6).number_format = "0"
        ws.cell(row=r, column=7, value=(
            f"=COUNTIFS(ProspectCalc!${PC['is_pql']}$2:${PC['is_pql']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['pql_date']}$2:${PC['pql_date']}${pc_last},\">=\"&{month_start},"
            f"ProspectCalc!${PC['pql_date']}$2:${PC['pql_date']}${pc_last},\"<\"&{month_end_excl},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=8, value=f"=G{r}/F{r}")
        ws.cell(row=r, column=8).number_format = PCT_FMT

        # Pipeline goal / actual / attainment — CRITICAL: a both-segment
        # prospect counts toward MQL AND PQL goals above (one prospect, two
        # counts, by design), but pipeline uses the UNION (is_opp, scoped by
        # qualified_date), never the sum of MQL+PQL pipeline, so it can't
        # double count the both-segment's dollars.
        ws.cell(row=r, column=9, value=f"=$B$3*B{r}")
        ws.cell(row=r, column=9).number_format = CURRENCY_FMT
        ws.cell(row=r, column=10, value=(
            f"=SUMIFS(ProspectCalc!${PC['pipeline_value']}$2:${PC['pipeline_value']}${pc_last},"
            f"ProspectCalc!${PC['is_opp']}$2:${PC['is_opp']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['qualified_date']}$2:${PC['qualified_date']}${pc_last},\">=\"&{month_start},"
            f"ProspectCalc!${PC['qualified_date']}$2:${PC['qualified_date']}${pc_last},\"<\"&{month_end_excl},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=10).number_format = CURRENCY_FMT
        ws.cell(row=r, column=11, value=f"=J{r}/I{r}")
        ws.cell(row=r, column=11).number_format = PCT_FMT

    data_end = data_start + len(FISCAL_MONTHS) - 1
    band_rows(ws, data_start, data_end, len(headers5))

    total_row5 = data_end + 1
    ws.cell(row=total_row5, column=1, value="Total").font = BOLD_FONT
    for c, letter in [(3, "C"), (4, "D"), (6, "F"), (7, "G"), (9, "I"), (10, "J")]:
        ws.cell(row=total_row5, column=c, value=f"=SUM({letter}{data_start}:{letter}{data_end})")
        ws.cell(row=total_row5, column=c).font = BOLD_FONT
        ws.cell(row=total_row5, column=c).number_format = CURRENCY_FMT if c in (9, 10) else "0"
    ws.cell(row=total_row5, column=5, value=f"=D{total_row5}/C{total_row5}")
    ws.cell(row=total_row5, column=8, value=f"=G{total_row5}/F{total_row5}")
    ws.cell(row=total_row5, column=11, value=f"=J{total_row5}/I{total_row5}")
    for c in (5, 8, 11):
        ws.cell(row=total_row5, column=c).number_format = PCT_FMT
        ws.cell(row=total_row5, column=c).font = BOLD_FONT

    cross_check_row = total_row5 + 2
    ws.cell(row=cross_check_row, column=1,
        value=(f"Cross-check: Total Actual Pipeline above must equal Channel Summary's Total Pipeline "
               f"(=Channel Summary!F{total_row})."))
    ws.cell(row=cross_check_row, column=1).font = Font(name=FONT_NAME, size=11, italic=True, color="808080")
    ws.merge_cells(start_row=cross_check_row, start_column=1, end_row=cross_check_row, end_column=len(headers5))

    # Conditional formatting for the three attainment columns
    green_fill = PatternFill("solid", start_color="C6EFCE")
    green_font = Font(name=FONT_NAME, color="006100")
    yellow_fill = PatternFill("solid", start_color="FFEB9C")
    yellow_font = Font(name=FONT_NAME, color="9C6500")
    red_fill = PatternFill("solid", start_color="FFC7CE")
    red_font = Font(name=FONT_NAME, color="9C0006")

    for col_letter in ("E", "H", "K"):
        rng = f"{col_letter}{data_start}:{col_letter}{data_end}"
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="greaterThanOrEqual", formula=["0.95"], fill=green_fill, font=green_font))
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="between", formula=["0.8", "0.949999999"], fill=yellow_fill, font=yellow_font))
        ws.conditional_formatting.add(rng,
            CellIsRule(operator="lessThan", formula=["0.8"], fill=red_fill, font=red_font))

    autofit(ws, len(headers5))
    ws.freeze_panes = "A2"

    # ------------------------------------------------------------------
    # Fill TAB 6 — Deal Efficiency (fiscal-window scoped; cycle days
    # computed from real per-opportunity data, not a static benchmark)
    # ------------------------------------------------------------------
    ws = ws_deal
    ws.cell(row=1, column=1, value="Metrics by seniority tier (fiscal window only)")
    headers6a = ["Tier", "Leads", "MQLs", "SQLs", "Closed-won", "Avg deal size",
                  "Avg sales cycle (days)", "Win rate", "Lead to MQL %", "MQL to SQL %"]
    style_section_row(ws, 1, len(headers6a))

    header_row6 = 2
    for c, h in enumerate(headers6a, start=1):
        ws.cell(row=header_row6, column=c, value=h)
    style_header_row(ws, header_row6, len(headers6a))

    data_start6 = header_row6 + 1
    for i, (display, tier_val) in enumerate(TIER_DISPLAY):
        r = data_start6 + i
        ws.cell(row=r, column=1, value=display)
        ws.cell(row=r, column=2, value=(
            f"=COUNTIFS(ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['first_touch_date']}$2:${PC['first_touch_date']}${pc_last},\">=\"&{FISCAL_START_DATE},"
            f"ProspectCalc!${PC['first_touch_date']}$2:${PC['first_touch_date']}${pc_last},\"<\"&{FISCAL_END_DATE_EXCL},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=3, value=(
            f"=COUNTIFS(ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['is_mql']}$2:${PC['is_mql']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\">=\"&{FISCAL_START_DATE},"
            f"ProspectCalc!${PC['mql_date']}$2:${PC['mql_date']}${pc_last},\"<\"&{FISCAL_END_DATE_EXCL},"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=4, value=(
            f"=COUNTIFS(ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['is_opp']}$2:${PC['is_opp']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=5, value=(
            f"=COUNTIFS(ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['is_closed_won']}$2:${PC['is_closed_won']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=6, value=(
            f"=AVERAGEIFS(ProspectCalc!${PC['pipeline_value']}$2:${PC['pipeline_value']}${pc_last},"
            f"ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['is_closed_won']}$2:${PC['is_closed_won']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=6).number_format = CURRENCY_FMT
        # Avg sales cycle now computed from the real per-opportunity cycle_days
        # field (seniority base + lead_type addend, +/-15% noise) instead of a
        # static benchmark dict.
        ws.cell(row=r, column=7, value=(
            f"=AVERAGEIFS(ProspectCalc!${PC['cycle_days']}$2:${PC['cycle_days']}${pc_last},"
            f"ProspectCalc!${PC['seniority_tier']}$2:${PC['seniority_tier']}${pc_last},\"{tier_val}\","
            f"ProspectCalc!${PC['is_opp']}$2:${PC['is_opp']}${pc_last},TRUE,"
            f"ProspectCalc!${PC['in_fiscal_window']}$2:${PC['in_fiscal_window']}${pc_last},TRUE)"))
        ws.cell(row=r, column=7).number_format = "0.0"
        ws.cell(row=r, column=8, value=f"=E{r}/D{r}")
        ws.cell(row=r, column=8).number_format = PCT_FMT
        ws.cell(row=r, column=9, value=f"=C{r}/B{r}")
        ws.cell(row=r, column=9).number_format = PCT_FMT
        ws.cell(row=r, column=10, value=f"=D{r}/C{r}")
        ws.cell(row=r, column=10).number_format = PCT_FMT

    data_end6 = data_start6 + len(TIER_DISPLAY) - 1
    band_rows(ws, data_start6, data_end6, len(headers6a))

    section2_row = data_end6 + 2
    ws.cell(row=section2_row, column=1, value="Channel role reference table")
    headers6b = ["Channel", "Role", "Motion", "CPL benchmark", "ROAS benchmark"]
    style_section_row(ws, section2_row, len(headers6b))

    header_row6b = section2_row + 1
    for c, h in enumerate(headers6b, start=1):
        ws.cell(row=header_row6b, column=c, value=h)
    style_header_row(ws, header_row6b, len(headers6b))

    role_data = [
        ("LinkedIn", "Demand generation", "Both", "$80-$130", "3-4x"),
        ("Google Ads", "Demand capture", "Both", "$75-$200", "3-4x"),
        ("G2", "Closing validator", "Both", "Not applied", "Not applied"),
        ("Programmatic", "Air cover / ABM", "Sales-assisted", "Not applied", "Not applied"),
    ]
    data_start6b = header_row6b + 1
    for i, row in enumerate(role_data):
        r = data_start6b + i
        for c, val in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=val)
    data_end6b = data_start6b + len(role_data) - 1
    band_rows(ws, data_start6b, data_end6b, len(headers6b))

    autofit(ws, max(len(headers6a), len(headers6b)))
    ws.freeze_panes = "A2"

    wb.save(OUT_XLSX)
    print(f"Wrote {OUT_XLSX}")


if __name__ == "__main__":
    main()
